ddmani_blog_homepage:
    pattern:  /
    defaults: { _controller: ddmaniBlogBundle:Blog:index }

ddmani_blog_post:
    pattern:  /postpage/{id}/
    defaults: { _controller: ddmaniBlogBundle:Blog:postshow }

ddmani_blog_backoffice:
    pattern:  /admin/
    defaults: { _controller: ddmaniBlogBundle:BlogAdmin:index }

