parameters:
#    ddmani_blog.example.class: ddmani\BlogBundle\Example
    posts.maxlinesperpage: 10 

services:
#    ddmani_blog.example:
#        class: %ddmani_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
