<?php

namespace ddmani\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    private $qb;
    public function PostCommentList($id){
        $this->qb = $this->createQueryBuilder('c')
                         ->add('select', 'c')
                         ->where("c.commentPost = :id")
                         ->setParameter('id',$id)
                         ->orderBy('c.commentDateCreate', 'ASC')
                         ->getQuery();
        return $this->qb->getResult();
    }
}
